function lovelicense(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',Hb='&',ic='.cache.html',db='/',pb='//',ac='12AE787E193AF9C15C5622943AEB02E2',dc='21012AA73312DF55129DDA29F0327F5B',ec='4036C54600822C68C0F1A70517F04C63',fc='58A41CAB2D5C52F1341A35E3904C8C6F',hc=':',bc=':1',cc=':2',tb='::',qc='<script defer="defer">lovelicense.onInjectionDone(\'lovelicense\')<\/script>',lb='<script id="',wb='=',cb='?',gc='B50FFC5BF08B95C1F630CFE55A13D31D',yb='Bad handler "',pc='DOMContentLoaded',nb='SCRIPT',kb='__gwt_marker_lovelicense',Nb='android',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',vb='content',Ob='desktop',ab='end',Gb='formfactor',Wb='gecko',Xb='gecko1_8',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',jc='gwt/clean/clean.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',oc='head',$b='hosted.html?lovelicense',nc='href',Tb='ie10',Vb='ie8',Ub='ie9',Cb='iframe',eb='img',Lb='ipad',Ib='iphone',Jb='ipod',Db="javascript:''",kc='link',Zb='loadExternalRefs',U='lovelicense',ib='lovelicense.nocache.js',sb='lovelicense::',qb='meta',Kb='mobile',Fb='moduleRequested',_='moduleStartup',Sb='msie',rb='name',Eb='position:absolute;width:0;height:0;border:none',lc='rel',Rb='safari',hb='script',_b='selectingPermutation',V='startup',mc='stylesheet',Mb='tablet',jb='undefined',Yb='unknown',Pb='user.agent',Qb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}lovelicense=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=J(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a){var b=u[a];return b==null?null:b}
function K(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){var a=location.search;var b=a.indexOf(Gb);if(b>=0){var c=a.substring(b);var d=c.indexOf(wb)+1;var e=c.indexOf(Hb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Ib)!=-1||f.indexOf(Jb)!=-1){return Kb}else if(f.indexOf(Lb)!=-1){return Mb}else if(f.indexOf(Nb)!=-1||f.indexOf(Kb)!=-1){var g=160;var h=m.screen.width/g;var i=m.screen.height/g;var j=Math.sqrt(h*h+i*i);return j<6?Kb:Mb}return Ob};v[Gb]={desktop:0,mobile:1,tablet:2};w[Pb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Qb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=10}())return Tb;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=9}())return Ub;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=8}())return Vb;if(function(){return b.indexOf(Wb)!=-1}())return Xb;return Yb};v[Pb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};lovelicense.onScriptLoad=function(){if(M){r=true;G()}};lovelicense.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Zb,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=$b;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:_b});if(!F()){try{K([Ob,Ub],ac);K([Kb,Ub],ac+bc);K([Mb,Ub],ac+cc);K([Ob,Rb],dc);K([Kb,Rb],dc+bc);K([Mb,Rb],dc+cc);K([Ob,Vb],ec);K([Kb,Vb],ec+bc);K([Mb,Vb],ec+cc);K([Ob,Tb],fc);K([Kb,Tb],fc+bc);K([Mb,Tb],fc+cc);K([Ob,Xb],gc);K([Kb,Xb],gc+bc);K([Mb,Xb],gc+cc);O=A[L(Gb)][L(Pb)];var Q=O.indexOf(hc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+ic}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[jc]){var a=n.createElement(kc);__gwt_stylesLoaded[jc]=a;a.setAttribute(lc,mc);a.setAttribute(nc,t+jc);n.getElementsByTagName(oc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(pc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(pc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Zb,millis:(new Date).getTime(),type:X});n.write(qc)}
lovelicense();