function lovelicense(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Bb='&',hc='.cache.html',$='/',$b='2669220D2BA9199955005AAB3127B27B',bc='3B76D3625618B7553A1809B5BDAA45C9',cc='74CD7257E81506A7F9FD97662340F2C8',dc='8F24C7140935E5EC4604207048E51435',gc=':',_b=':1',ac=':2',nb='::',pc='<script defer="defer">lovelicense.onInjectionDone(\'lovelicense\')<\/script>',gb='<script id="',qb='=',Z='?',ec='A0557FA257A2C9DA4EDA5F4D33A2A212',Nb='ActiveXObject',sb='Bad handler "',Ob='ChromeTab.ChromeFrame',oc='DOMContentLoaded',fc='F2D3C37CF8B0527C99F9F43244BACB38',ib='SCRIPT',fb='__gwt_marker_lovelicense',Hb='android',jb='base',bb='baseUrl',S='begin',R='bootstrap',Mb='chromeframe',ab='clear.cache.gif',pb='content',Ib='desktop',X='end',Ab='formfactor',Ub='gecko',Vb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',ic='gwt/clean/clean.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',nc='head',Yb='hosted.html?lovelicense',mc='href',Tb='ie6',Sb='ie8',Rb='ie9',wb='iframe',_='img',Fb='ipad',Cb='iphone',Db='ipod',xb="javascript:''",jc='link',Xb='loadExternalRefs',P='lovelicense',db='lovelicense.nocache.js',mb='lovelicense::',kb='meta',Eb='mobile',zb='moduleRequested',W='moduleStartup',Qb='msie',lb='name',Kb='opera',yb='position:absolute;width:0;height:0;border:none',kc='rel',Pb='safari',cb='script',Zb='selectingPermutation',Q='startup',lc='stylesheet',Gb='tablet',eb='undefined',Wb='unknown',Jb='user.agent',Lb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}lovelicense=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){var a=location.search;var b=a.indexOf(Ab);if(b>=0){var c=a.substring(b);var d=c.indexOf(qb)+1;var e=c.indexOf(Bb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Cb)!=-1||f.indexOf(Db)!=-1){return Eb}else if(f.indexOf(Fb)!=-1){return Gb}else if(f.indexOf(Hb)!=-1||f.indexOf(Eb)!=-1){var g=160;var h=l.screen.width/g;var i=l.screen.height/g;var j=Math.sqrt(h*h+i*i);return j<6?Eb:Gb}return Ib};u[Ab]={desktop:0,mobile:1,tablet:2};v[Jb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Kb)!=-1}())return Kb;if(function(){return c.indexOf(Lb)!=-1||function(){if(c.indexOf(Mb)!=-1){return true}if(typeof window[Nb]!=eb){try{var b=new ActiveXObject(Ob);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Pb;if(function(){return c.indexOf(Qb)!=-1&&m.documentMode>=9}())return Rb;if(function(){return c.indexOf(Qb)!=-1&&m.documentMode>=8}())return Sb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Tb;if(function(){return c.indexOf(Ub)!=-1}())return Vb;return Wb};u[Jb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};lovelicense.onScriptLoad=function(){if(H){q=true;B()}};lovelicense.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Xb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Yb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Zb});if(!A()){try{F([Ib,Tb],$b);F([Eb,Tb],$b+_b);F([Gb,Tb],$b+ac);F([Ib,Sb],bc);F([Eb,Sb],bc+_b);F([Gb,Sb],bc+ac);F([Ib,Vb],cc);F([Eb,Vb],cc+_b);F([Gb,Vb],cc+ac);F([Ib,Pb],dc);F([Eb,Pb],dc+_b);F([Gb,Pb],dc+ac);F([Ib,Kb],ec);F([Eb,Kb],ec+_b);F([Gb,Kb],ec+ac);F([Ib,Rb],fc);F([Eb,Rb],fc+_b);F([Gb,Rb],fc+ac);J=w[G(Ab)][G(Jb)];var L=J.indexOf(gc);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+hc}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[ic]){var a=m.createElement(jc);__gwt_stylesLoaded[ic]=a;a.setAttribute(kc,lc);a.setAttribute(mc,s+ic);m.getElementsByTagName(nc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(oc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(oc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Xb,millis:(new Date).getTime(),type:S});m.write(pc)}
lovelicense();